### ISSUE TITLE
Errors when running install script

### ISSUE THREAD

**Issue by mytechguyri** [jonesaaronj/asus-merlin-adblock#1]
I ran the install script, it got to the following point, then a bunch of errors.   This is on an ASUS AC-3200 running Asus Merlin version 384.6

`:: Creating adblock database
Error: near line 1: no such table: source
Error: near line 2: no such table: blocked
Error: near line 3: no such table: whitelist
Error: near line 4: no such table: blacklist
Error: near line 5: no such view: blocked_view
Error: near line 6: no such view: hosts_view
::: done.
:::
::: Creating adblock host file
IP: 192.168.1.254
Database: /opt/etc/adblock.db
Host file: /opt/etc/adblock.host
Clearing blocked table in /opt/etc/adblock.db
Downloading http://pgl.yoyo.org/adservers/serverlist.php

Fatal error: Uncaught Error: Call to undefined function curl_init() in /tmp/mnt/sda1/entware/asus-merlin-adblock/adblock.php:36
Stack trace:
#0 /tmp/mnt/sda1/entware/asus-merlin-adblock/adblock.php(109): curl_download('/opt/etc/adbloc...', 'http://pgl.yoyo...', '1')
#1 /tmp/mnt/sda1/entware/asus-merlin-adblock/adblock.php(135): load_blocked('/opt/etc/adbloc...')
#2 /tmp/mnt/sda1/entware/asus-merlin-adblock/adblock.php(152): main('192.168.1.254', '/opt/etc/adbloc...', '/opt/etc/adbloc...')
#3 {main}
  thrown in /tmp/mnt/sda1/entware/asus-merlin-adblock/adblock.php on line 36
::: done.
`

**Comment by mytechguyri** [comment]
Appears the problem is you're not installing php7-mod-curl among your dependencies.   Once I installed that, it completed successfully.

**Comment by jonesaaronj** [comment]
fixed
